# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('father_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('notif_type', models.CharField(choices=[('NON', 'none'), ('SMS', 'sms'), ('MAL', 'E-Mail'), ('BOT', 'both')], default='NON', max_length=3)),
            ],
        ),
    ]
