# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='id',
        ),
        migrations.AddField(
            model_name='cheque',
            name='cheque_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
