# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='first_nameeeee',
        ),
    ]
