# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170104_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='last_namesddss',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notif_type',
        ),
    ]
