# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170104_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='period_type',
            field=models.CharField(choices=[(b'da', b'daily'), (b'we', b'weekly'), (b'mo', b'monthly'), (b'yr', b'yearly')], default=b'yr', max_length=2),
        ),
    ]
