# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161231_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='branch_id',
            new_name='branch',
        ),
        migrations.AlterField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Employee'),
        ),
    ]
