# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paymentorder_period_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='amount',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
    ]
