# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20170104_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('R', 'real'), ('L', 'legal')], default='R', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('social_id', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_owners', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='card', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CardToCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('atm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_to_cards', to='core.ATM')),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('social_id', models.CharField(max_length=10, unique=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Branch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('cheque_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChequeApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_expert_validation', models.CharField(choices=[('NA', 'unknown'), ('AC', 'accepted'), ('RE', 'rejected')], default='NA', max_length=2)),
                ('auditor_validation', models.CharField(choices=[('NA', 'unknown'), ('AC', 'accepted'), ('RE', 'rejected')], default='NA', max_length=2)),
                ('date', models.DateField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_books', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('legal_expert_validation', models.BooleanField(default=False)),
                ('auditor_validation', models.BooleanField(default=False)),
                ('cheque', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issue', to='core.Cheque')),
                ('dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('atm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.ATM')),
            ],
        ),
        migrations.CreateModel(
            name='Greenback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NA', 'unknown'), ('AC', 'accepted'), ('RE', 'rejected')], default='NA', max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Jursit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('social_id', models.CharField(max_length=10, unique=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Branch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_payments', models.IntegerField()),
                ('interest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('payment_count', models.IntegerField()),
                ('legal_expert_validation', models.CharField(choices=[('NA', 'unknown'), ('AC', 'accepted'), ('RE', 'rejected')], default='NA', max_length=2)),
                ('auditor_validation', models.CharField(choices=[('NA', 'unknown'), ('AC', 'accepted'), ('RE', 'rejected')], default='NA', max_length=2)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_applications', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('social_id', models.CharField(max_length=10, unique=True)),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Branch')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1023)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PayedBill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_info', to='core.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_from', to='core.Account')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders_to', to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_production_fee', models.IntegerField(default=100)),
                ('cheque_production_fee', models.IntegerField(default=100)),
                ('sms_notif_fee', models.IntegerField(default=100)),
                ('card_to_card_fee', models.IntegerField(default=100)),
                ('transactio_fee', models.IntegerField(default=100)),
                ('atm_min_money', models.IntegerField(default=100000)),
                ('loan_interest', models.FloatField(default=0.14)),
                ('deposit_yearly_interest', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('w', 'withdraw'), ('d', 'deposit')], max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.Account')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.Auditor')),
                ('branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='core.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionWage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wage_type', models.CharField(choices=[('CTC', 'card to card'), ('TRN', 'transaction')], max_length=3)),
                ('amount', models.IntegerField()),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wage', to='core.Transaction')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawFromATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ATM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawals', to='core.ATM')),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='core.Card')),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_nameeeee',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_namesddss',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='notif_type',
            field=models.CharField(choices=[('NON', 'none'), ('SMS', 'sms'), ('MAL', 'E-Mail'), ('BOT', 'both')], default='NON', max_length=3),
        ),
        migrations.AddField(
            model_name='payedbill',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Transaction'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='loan', to='core.LoanApplication'),
        ),
        migrations.AddField(
            model_name='contain',
            name='greenback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Greenback'),
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Transaction'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='cheque_application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_pages', to='core.ChequeApplication'),
        ),
        migrations.AddField(
            model_name='cardtocard',
            name='deposit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Transaction'),
        ),
        migrations.AddField(
            model_name='cardtocard',
            name='from_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_cards', to='core.Card'),
        ),
        migrations.AddField(
            model_name='cardtocard',
            name='to_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_cards', to='core.Card'),
        ),
        migrations.AddField(
            model_name='cardtocard',
            name='withdraw',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Transaction'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.Manager'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='core.BillType'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Branch'),
        ),
        migrations.AddField(
            model_name='auditor',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atm',
            name='greenback',
            field=models.ManyToManyField(related_name='_atm_greenback_+', through='core.Contain', to='core.Greenback'),
        ),
        migrations.AddField(
            model_name='atm',
            name='maintainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atms', to='core.Maintainer'),
        ),
        migrations.AddField(
            model_name='account',
            name='real_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='core.Customer'),
        ),
    ]
