# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161231_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[(b'au', b'auditor'), (b'ca', b'cashier'), (b'ma', b'manager'), (b'le', b'legal')], default=b'cashier', max_length=2),
        ),
        migrations.AlterField(
            model_name='employee',
            name='social_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
