# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170104_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='card_production_fee',
        ),
        migrations.AddField(
            model_name='system',
            name='card_productionnn_fee',
            field=models.IntegerField(default=100),
        ),
    ]
