# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20170101_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ATMGuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ATM', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atm_guy', to='core.ATM')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atm_guy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CardToCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('ATM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_to_card', to='core.ATM')),
                ('FromCard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_to_card_from', to='core.Card')),
                ('ToCard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_to_card_to', to='core.Card')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
                ('father_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='eskenas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='withdrawFromATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField()),
                ('ATM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='core.ATM')),
                ('Card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal', to='core.Card')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='billType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='core.BillType'),
        ),
    ]
