# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 12:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170101_0750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.IntegerField(primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining_payment', models.IntegerField()),
                ('interest', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.BigIntegerField()),
                ('payment_count', models.IntegerField()),
                ('legal_expert_confirmation', models.BooleanField(default=False)),
                ('auditor_confirmation', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Account')),
            ],
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_production_fee', models.IntegerField(default=0)),
                ('check_production_fee', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='eskenas',
            new_name='Greenback',
        ),
        migrations.RenameField(
            model_name='bill',
            old_name='billType',
            new_name='bill_type',
        ),
        migrations.RenameField(
            model_name='cardtocard',
            old_name='FromCard',
            new_name='from_card',
        ),
        migrations.RenameField(
            model_name='cardtocard',
            old_name='ToCard',
            new_name='to_card',
        ),
        migrations.RenameField(
            model_name='withdrawfromatm',
            old_name='Card',
            new_name='card',
        ),
        migrations.RemoveField(
            model_name='card',
            name='cardNumber',
        ),
        migrations.RemoveField(
            model_name='cardtocard',
            name='ATM',
        ),
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[(b'au', b'auditor'), (b'ca', b'cashier'), (b'ma', b'manager'), (b'le', b'legal expert')], default=b'ca', max_length=2),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.LoanApplication'),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Account'),
        ),
    ]
