# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170104_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='system',
            old_name='card_productionnn_fee',
            new_name='card_production_fee',
        ),
    ]
