# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_withdrawfromatm_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_production_fee', models.IntegerField(default=100)),
                ('cheque_production_fee', models.IntegerField(default=100)),
                ('sms_notif_fee', models.IntegerField(default=100)),
                ('card_to_card_fee', models.IntegerField(default=100)),
                ('transactio_fee', models.IntegerField(default=100)),
                ('atm_min_money', models.IntegerField(default=100000)),
                ('loan_interest', models.FloatField(default=0.14)),
                ('deposit_yearly_interest', models.FloatField(default=0.14, help_text=b' Implemented yearly, but must be applied daily(x^(1/365))')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='System',
        ),
    ]
