# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170104_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contain',
            unique_together=set([('greenback', 'atm')]),
        ),
    ]
