# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 12:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170104_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditor',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='jursit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='branch',
        ),
    ]
